blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path(
        '',
        RedirectView.as_view(url='/1'),
        name='index'
    ),
    path(
        '<int:page>',
        views.ArticleListView.as_view(),
        name='article_list'
    ),
    path(
        'article/<int:article_id>',
        views.ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/<int:article_id>/edit',
        views.manage_article_view,
        name='article_edit'
    ),
    path(
        'article/create',
        views.manage_article_view,
        name='article_create',
        kwargs={'article_id': None}
    ),
    path(
        'category_list',
        views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        'category/<int:category_id>/<int:page>/',
        views.CategoryDetailView.as_view(),
        name='category_detail'
    )
    ]

comments/urls.py
from django.urls import path

from comments.views import CommentPostView

app_name = 'comments'
urlpatterns = [
    path(
        'article/<int:article_id>/postcomment',
        CommentPostView.as_view(),
        name='comment_post'
         )
]

myblog/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import RegisterView

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    re_path(r'', include('accounts.urls', namespace='accounts')),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'', include('comments.urls', namespace='comments'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models

from accounts.models import BlogUser
from blog.models import Article


# Create your models here.
class Comment(models.Model):
    author = models.ForeignKey(
        BlogUser,
        verbose_name='Author',
        on_delete=models.CASCADE
    )
    article = models.ForeignKey(
        Article,
        verbose_name='Article',
        on_delete=models.CASCADE
    )
    parent_comment = models.ForeignKey(
        'self',
        verbose_name='Parent',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    is_enable = models.BooleanField(
        'is_enable',
        default=True,
        blank=False,
        null=False
    )
    body = models.TextField('Body')

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = verbose_name
        ordering = ['id']
        get_latest_by = 'id'

    @property
    def death(self):
        """
        Return _death summed with 1 (for display in template)
        """

        return self._death + 1

    def __init__(self, *args, **kwargs):
        super(Comment, self).__init__(*args, **kwargs)
        if self.parent_comment:
            self._death = self.parent_comment.death
        else:
            self._death = 0

    def __str__(self):
        return self.body

comments/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import widgets

from .models import Comment


class CommentPostForm(ModelForm):
    parent_comment_id = forms.IntegerField(
        widget=widgets.HiddenInput, required=False
    )

    class Meta:
        model = Comment
        fields = ['body']

comments/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.contrib.auth import get_user

from .forms import CommentPostForm
from blog.models import Article
from .models import Comment


# Create your views here.
class CommentPostView(FormView):
    form_class = CommentPostForm
    template_name = "comments/comment_creation_form.html"
    # todo: redirect to a article
    success_url = '/'
    user = None

    def form_valid(self, form):
        if form.is_valid():
            article_id = self.kwargs.get("article_id")
            article = Article.objects.get(pk=article_id)

            comment = form.save(False)

            comment.article = article
            comment.author = self.user

            if parent_comment_id := form.cleaned_data["parent_comment_id"]:
                parent_comment = Comment.objects.get(pk=parent_comment_id)
                comment.parent_comment = parent_comment

            form.instanace = comment

            form.save()

            # return super(CommentPostView, self).form_valid(form)
            return HttpResponseRedirect(f"/article/{article_id}")

        else:
            return self.render_to_response({'form': form})

    def post(self, request, *args, **kwargs):
        self.user = get_user(request)

        return super(CommentPostView, self).post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.user = get_user(request)

        return super(CommentPostView, self).get(request, *args, **kwargs)

comments/templates/comments/comment.html
{% load comment_tags %}
{% load blog_tags %}

<div class="comment-content-block">
    <a class="comment-author-url h4"
       href="{{ comment.author.get_profile_url }}">
        {{ comment.author }}
    </a>
    <div class="comment-body">
        {{ comment.body }}
    </div>
    {% if user.is_authenticated %}
        <div id="comment-{{ comment.id }}" class="comment">
            <a id="comment-{{ comment.id }}-reply-link" class="reply" onclick="reply_to({{ comment.id }})">reply</a>
        </div>
    {% endif %}
        {% query comments_to_self_article  parent_comment=comment as children_comments %}
        {% if children_comments %}
            <div class="comment-children-block">
            {% with children_comments_count=children_comments|length %}
            {% for child in children_comments %}
                {% with comment=child template_name='comments/comment.html' %}
                    {% if children_comments_count > 1 and forloop.counter0 != 0%}
                        <div class="comment-child" style="border-top: 2px solid #000;">
                    {% else %}
                        <div class="comment-child">
                    {% endif %}

                    {% if depth >= 1 %}
                        {% include template_name %}
                    {% else %}
                        {% with depth=depth|add:2 %}
                            {% include template_name %}
                        {% endwith %}
                    {% endif %}
                    </div>
                {% endwith %}
            {% endfor %}
            {% endwith %}
            </div>
        {% endif %}
</div>

comments/templates/comments/comment_creation_form.html
<form id="comment-creation-form" action="{% url 'comments:comment_post' article.id %}" method="post" class="comment-creation-form" id="comment-create">
    {% csrf_token %}
    {{ form.body }}
    {{ form.body.errors }}
    {{ form.parent_comment_id }}
    <button type="submit" class="comment-submit">Send</button>
</form>

comments/templates/comments/comment_list.html
<!-- todo: add line at the left of comments for display children -->
<!-- todo: fix comment death: irregular adding comments to the comments -->

<section class="comments">
    <h1>Comments:</h1>
    <div class="container">
        {% load comment_tags %}
        {% load blog_tags %}

        {% query comments_to_self_article parent_comment=None as parent_comments %}

        {% for comment in parent_comments %}
            {% with depth=0 %}
                {% include 'comments/comment.html' %}
            {% endwith %}
        {% endfor %}
    </div>
</section>