blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path(
        '',
        RedirectView.as_view(url='/1'),
        name='index'
    ),
    path(
        '<int:page>',
        views.ArticleListView.as_view(),
        name='article_list'
    ),
    path(
        'article/<int:article_id>',
        views.ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/<int:article_id>/edit',
        views.manage_article_view,
        name='article_edit'
    ),
    path(
        'article/create',
        views.manage_article_view,
        name='article_create',
        kwargs={'article_id': None}
    ),
    path(
        'category_list',
        views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        'category/<int:category_id>/<int:page>/',
        views.CategoryDetailView.as_view(),
        name='category_detail'
    )
    ]

myblog/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import RegisterView

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    re_path(r'', include('accounts.urls', namespace='accounts')),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'', include('comments.urls', namespace='comments'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import logging
import ast

from django.conf import settings
from django.contrib.auth.models import AnonymousUser
from django.db.models import QuerySet
from django.db import models
from django.utils import timezone
from myblog.settings import LENGTH_SHORT_BODY
from mdeditor.fields import MDTextField

from accounts.models import BlogUser

logger = logging.getLogger(__name__)


class Article(models.Model):
    """
    Author, title, body, category are required. Other are optional
    Important! Don't update status directly. Use set_status
    """

    STATUS_CHOICES = (('p', 'Published'), ('d', 'Draft'))

    id = models.BigAutoField(primary_key=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="author",
        verbose_name='Author',
        blank=False,
        null=False,
        default=None,
        limit_choices_to={'is_author': True},
        on_delete=models.CASCADE
    )

    category = models.ForeignKey(
        'blog.Category',
        verbose_name='Category',
        blank=False,
        null=False,
        default=None,
        on_delete=models.CASCADE
    )

    title = models.CharField(max_length=100, null=False, blank=False)
    body = MDTextField('Body', null=False, blank=False)

    publish = models.DateTimeField(default=timezone.now, editable=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(default=timezone.now, editable=False)

    # Important! Don't update status directly. Use set_status
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='d',
        editable=False
    )

    viewed_users = models.ManyToManyField(
        BlogUser,
        related_name="viewed_users"
    )

    class Meta:
        ordering = ['-publish']
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    def __str__(self):
        return self.title

    def save(
            self,
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None,
    ):
        if update_fields and not (
            "viewed_users_list" in update_fields and
            len(update_fields) == 1
        ):
            self.updated = timezone.now()

        super(Article, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    def set_status(self, new_status: str) -> None:
        """ Realize autoupdate publish time """
        if self.status == new_status:
            return

        if new_status == 'p':
            self.status = new_status
            self.publish = timezone.now()
        elif new_status == 'd':
            self.status = new_status
        else:
            raise ValueError(
                "new_status must be 'p' or 'd'. Got a {0}".format(new_status)
            )

        self.save()

    def register_view(self, user: BlogUser or AnonymousUser) -> None:
        """ Add present user to viewed_user, if he isn't in it"""
        self_article = Article.objects.get(id=self.id)

        if isinstance(user, BlogUser) and \
                user.username not in self_article.viewed_users.all():
            self_article.viewed_users.add(user)
            self_article.save()
        elif isinstance(user, BlogUser) and user.username in self.viewed_users:
            return
        elif isinstance(user, AnonymousUser):
            return
        else:
            raise ValueError(f"Required BlogUser, excepted {type(user)}")

    @property
    def views_count(self):
        return self.viewed_users.all().count()

    @property
    def comments_to_self_article(self) -> QuerySet:
        comments = self.comment_set.filter(is_enable=True)
        return comments

    @property
    def short_body(self):
        return self.body[0:LENGTH_SHORT_BODY]


# todo: create validator for name (one of parameters is dont start with spaces)
class Category(models.Model):
    """ Storage articles. Name required. """
    id = models.BigAutoField(primary_key=True)

    name = models.CharField(
        'name',
        max_length=40,
        null=False,
        unique=True,
        blank=False,
        default=None
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

comments/models.py
from django.db import models

from accounts.models import BlogUser
from blog.models import Article


# Create your models here.
class Comment(models.Model):
    author = models.ForeignKey(
        BlogUser,
        verbose_name='Author',
        on_delete=models.CASCADE
    )
    article = models.ForeignKey(
        Article,
        verbose_name='Article',
        on_delete=models.CASCADE
    )
    parent_comment = models.ForeignKey(
        'self',
        verbose_name='Parent',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    is_enable = models.BooleanField(
        'is_enable',
        default=True,
        blank=False,
        null=False
    )
    body = models.TextField('Body')

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = verbose_name
        ordering = ['id']
        get_latest_by = 'id'

    @property
    def death(self):
        """
        Return _death summed with 1 (for display in template)
        """

        return self._death + 1

    def __init__(self, *args, **kwargs):
        super(Comment, self).__init__(*args, **kwargs)
        if self.parent_comment:
            self._death = self.parent_comment.death
        else:
            self._death = 0

    def __str__(self):
        return self.body

blog/forms.py
from django.forms import ModelForm
from .models import Article
from mdeditor.widgets import MDEditorWidget


class ArticleManagementForm(ModelForm):
    """ Uses for creation and edition articles. """

    def __init__(self, *args, **kwargs):
        super(ArticleManagementForm, self).__init__(*args, **kwargs)
        self.fields['body'].widget = MDEditorWidget(attrs={'rows': 30})

    class Meta:
        model = Article
        fields = ['title', 'body', 'category']

blog/views.py
# todo: add tests
# todo: add cache
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist

from myblog.settings import ERROR_MESSAGES
from myblog.utils import error_page
from .models import Article, Category
from .forms import ArticleManagementForm
from comments.forms import CommentPostForm


class ArticleListView(ListView):
    """ It's index page. Queryset restricted to only published. """

    template_name = 'blog/article_list.html'
    model = Article
    context_object_name = 'article_list'
    paginate_by = settings.PAGINATE_BY
    page_kwarg = 'page'

    def get_queryset(self):
        article_list = super(ArticleListView, self).get_queryset()
        article_list = article_list.filter(status="p")
        return article_list


class ArticleDetailView(DetailView):
    """ View of detail article. Also uses to view comments to article """
    template_name = "blog/article_detail.html"
    model = Article
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get(self, request, *args, **kwargs):
        user = get_user(request)

        obj = self.get_object()
        obj.register_view(user)

        return super(ArticleDetailView, self).get(request)

    def get_context_data(self, **kwargs):
        comment_form = CommentPostForm()

        kwargs['form'] = comment_form
        kwargs['comments_to_self_article'] = \
            self.object.comments_to_self_article

        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryListView(ListView):
    """ Storage of all categories. Queryset is sorted by abc """
    template_name = "blog/category_list.html"
    model = Category
    context_object_name = "category_list"

    def get_queryset(self):
        category_list = super(CategoryListView, self).get_queryset()
        category_list = category_list.order_by("name")
        return category_list


class CategoryDetailView(ListView):
    """ Uses to storage and show articles inhered to same category """
    template_name = "blog/category_detail.html"
    model = Article
    context_object_name = "article_list"
    page_kwarg = "page"
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        article_list = super(CategoryDetailView, self).get_queryset()

        queryset_id = self.kwargs["category_id"]
        category = get_object_or_404(Category, id=queryset_id)

        article_list = article_list.filter(
            status="p",
            category=category
        )

        return article_list

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset_id = self.kwargs["category_id"]
        category = get_object_or_404(Category, id=queryset_id)

        kwargs["category"] = category
        return super(CategoryDetailView, self).get_context_data(
            object_list=object_list,
            **kwargs
        )


def manage_article_view(request, article_id=None):
    # Edition article, if can
    if article_id:
        return edition_article(request, article_id)
    # Creation article
    else:
        return creation_article(request)


def article_form(request, article):
    form = ArticleManagementForm(instance=article)
    return render(
        request,
        'blog/article_form.html',
        {'form': form}
    )


def creation_article(request):
    article = Article()

    # GET requests handler
    if request.method == "GET":
        return article_form(request, article)

    # POST and PUT requests handler
    if request.method in ("POST", "PUT"):
        form = ArticleManagementForm(request.POST, instance=article)

        if form.is_valid():
            article = form.save(False)
            user = get_user(request)

            if user.is_author:
                article.author = user
            else:
                raise PermissionError("User isn't author")

            form.instance = article
            form.save()

            article = form.save(False)
            article_id = article.id

            return HttpResponseRedirect(reverse(
                "article_detail",
                kwargs={"article_id": article_id}
            ))

        else:
            return render(
                request,
                'blog/article_form.html',
                {'form': form}

            )


def edition_article(request, article_id):
    # Trying to get article
    try:
        article = Article.objects.get(id=article_id)
    except ObjectDoesNotExist:
        return error_page(
            request,
            ERROR_MESSAGES["Edit nonexistent article"]
        )

    # GET request handler
    if request.method == "GET":
        return article_form(request, article)

    # POST and PUT requests handler
    if request.method in ("POST", "PUT"):
        # Checks of user on permissions.
        user = get_user(request)
        if user != article.author or not (user.is_superuser
                                          or user.is_moderator):
            return error_page(request, ERROR_MESSAGES["Permission denied"])

        form = ArticleManagementForm(request.POST, instance=article)

        # Delete article, if it needs
        if request.POST.get("delete"):
            article = form.save(False)
            article.delete()

            return HttpResponseRedirect('/')

        if form.is_valid():
            if new_status := request.POST.get("publish" or "draft"):
                article.set_status(new_status)

            form.save()

            return HttpResponseRedirect(f'/article/{article_id}')
        else:
            return render(
                request,
                'blog/article_form.html',
                {
                    'form': form,
                    'author': article.author
                }
            )

blog/templates/blog/article_content.html
{% load blog_tags %}
<div class="title">
    <h1>{{article.title}}</h1>
</div>
<div class="body">
    {% autoescape off %}
        {% get_html_from_markdown article.body %}
    {% endautoescape %}
</div>
<!-- body -->

blog/templates/blog/article_detail.html
{% extends 'share_layout/base.html' %}
{% load static %}
{% load blog_tags %}
{% block header %}
    <link type="text/css"
          rel="stylesheet" href="{% static 'comments/comment_list/css/comment_list.css' %}">
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
    <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet">
    <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <script src="{% static 'comments/comment_list/js/reply.js' %}"></script>
{% if article.status == 'p' %}
    <div class="row">
        <div class="col-sm-8 article-main">
            {% if article.author == user or user.is_moderator or user.is_superuser %}
                <a href="/article/{{ article.id }}/edit">Edit</a>
            {% endif %}
            {% include 'blog/article_content.html' %}
        </div>
        <!-- article-main -->

        <!-- todo: restrict to 5 comments and after in new line -->
        <div class="container col-sm-5 comments-block">
            {% include 'comments/comment_list.html' %}
            {% if user.is_authenticated %}
                {% include 'comments/comment_creation_form.html' %}
            {% endif %}
            <!-- comments -->
        </div>
    </div>
    <!-- row -->
{% else %}
    {% if article.author == user %}
        <div class="row">
            <a href="/article/{{ article.id }}/edit">Edit</a>
            {% include 'blog/article_content.html' %}
            <div class="container col-sm-5 comments-block">
                {% include 'comments/comment_list.html' %}
                {% if user.is_authenticated %}
                    {% include 'comments/comment_creation_form.html' %}
                {% endif %}
                <!-- comments -->
            </div>
        </div>
    {% else %}
        <!-- todo: add redirect to error page -->
        Article have been deleted or hidden
    {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/article_edition_form.html
{% extends 'share_layout/base.html' %}
{% load static %}
{% block header %}
<meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
{% endblock %}
{% block content %}
{% if user.is_author %}
<div class="article-edition-form">
    <form class="form-edition" action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

        <script src="{% static 'blog/article_editor/js/remove_button.js' %}"></script>
        <button class="delete" name="del" value="delete">Delete</button>
        <button class="publish" type="submit">Submit</button>
    </form>
</div>
{% else %}
Access denied
{% endif %}

{% endblock %}

blog/templates/blog/article_form.html
{% extends 'share_layout/base.html' %}
{% load static %}
{% block header %}
<meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
{% endblock %}
{% block content %}
{% if user == author or user.is_moderator or user.is_superuser %}
<div class="article-edition-form">
    <form class="form-edition" action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

        <script src="{% static 'blog/article_editor/js/remove_button.js' %}"></script>
        <button class="publish" name="publish" value="p" type="submit">Publish</button>
        <button class="draft" name="draft" value="d" type="submit">Draft</button>
        <button class="delete" name="delete" value="delete" type="submit">Delete</button>
    </form>
</div>
{% else %}
Access denied
{% endif %}

{% endblock %}

blog/templates/blog/article_list.html
{% extends 'share_layout/base.html' %}

{% load static %}
{% load blog_tags %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/tags/article_info/css/article_info.css' %}">
{% endblock %}
{% block content %}
    <div class="articles">
        {% for article in article_list %}
            {% load_article_info article %}
        {% endfor %}
        {% if is_paginated %}
            {% load_pagination_info page_obj %}
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/category_detail.html
{% extends "share_layout/base.html" %}

{% load blog_tags %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/tags/article_info/css/article_info.css' %}">
{% endblock %}

{% block content %}
    <h1>{{ category.name }}</h1>
    <div class="articles">
        {% for article in article_list %}
            {% load_article_info article %}
        {% endfor %}
        {% if is_pagination %}
            {% load_pagination_info page_obj %}
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'share_layout/base.html' %}
{% load static %}
{% load blog_tags %}
{% block header %}
    <link type="text/css" rel="stylesheet" href="{% static 'blog/category_list/css/category_list.css' %}">
{% endblock %}
{% block content %}
    <div class="container categories">
        <h1>Categories</h1>
        <div class="category-list-container">
            {% for category in category_list %}
                <div class="category-name-container">
                    <a class="category-name h1"
                       href="{% url 'category_detail' category_id=category.id page=1 %}">{{ category.name }}</a>
                </div>
                {% autoescape off %}
                    {% return_br_if_residue_of_division_equal_zero forloop.counter 3 %}
                {% endautoescape %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>{{post.title}}</h1>
<a>{{post.body}}</a>
{% endblock %}